### ISSUE TITLE
Any way to isolate the art creation function?

### ISSUE THREAD

**Issue by JVTEAM** [maxvfischer/DIY-ai-art#36]
I'd like to just generate the art pictures without implementing the button and pir sensor.  What's the best way to go through a pull out the art generation function?

**Comment by maxvfischer** [comment]
Hi @JVTEAM

I've intentionally left out the code snippet that generates the art pieces that I'm using. The idea with this repository was to simplify for other digital artists to build their own AI art installation, and for them to use their own generative code in the installation.

If you want a function that generate art pieces similar to mine, you could do the following:

1. Scrape a lot of images of abstract art (e.g. from https://www.wikiart.org/)
2. Either implement your own StyleGAN/StyleGAN2 (or a similar generative neural network architecture), or use an open-source implementation (e.g. https://github.com/taki0112/StyleGAN-Tensorflow)
3. Train the network with your scraped images
4. Use your trained network to generate new images

I'm not sure if that answers your question?

**Comment by JVTEAM** [comment]
That explains why I couldn't find it skimming through the code.  Thanks!
