### ISSUE TITLE
Consider using HDMI-CEC

### ISSUE THREAD

**Issue by andystalick** [maxvfischer/DIY-ai-art#38]
You can control the TV power status by sending signals over HDMI

Check out https://github.com/Pulse-Eight/libcec and https://pimylifeup.com/raspberrypi-hdmi-cec/

Hardware support for Jetson may be lacking, but its worth checking into.

Of course, the TV is in "standby" mode and still does consume some power.

**Comment by maxvfischer** [comment]
Hey @andystalick 

I actually stumbled upon HDMI-CEC after I had finished implementing the screen saver solution. But I definitely agree, that's probably a more elegant solution.
